### ISSUE TITLE
Angular Document Web Autocapture height issue

### ISSUE THREAD

**Issue by simionrobert** [innovatrics/dot-web-samples#50]
I am using a Samsung S10e phone to test the Angular web component for document autocapture overlay.
Currently, there is an issue on the phone regarding the height of the document overlay. The overlay does not take the full height of the container as you can see in the image below. Also, when I close the phone and open it again, that missing space is moved below the overlay, not above as in the image. Is there a fix?
```
<div class="d-flex flex-column min-vh-100 justify-content-center align-items-center">
    <x-dot-document-auto-capture id="dot-document-auto-capture"></x-dot-document-auto-capture>
</div>
```
![image](https://user-images.githubusercontent.com/30863036/207409013-89949a37-122c-4f17-9274-854efa79269f.png)

**Comment by StigoSvK** [comment]
Hi @simionrobert
Height of camera element is relative to width by camera aspect ratio. Most camera will have 9/16 aspect ratio so if display has bigger aspect ratio (e.g. 9:18) and you set full container width, there will be always some margin. Otherwise, camera component would be stretched.

If you have any further questions, please contact us via [customer support](https://support.innovatrics.com/support/home)
This repo is only for demonstration purpose. Thanks
